media: public/assets
content: 
  - name: blog
    label: Articles
    type: collection
    path: src/content/blog
    fields:
      - { name: title, label: Title, type: string }
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date, options: { format: 'YYYY-MM-DDTHH:mm:ss[Z]' } }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: body, label: Body, type: rich-text }